ble:
  name_prefix: "ESP32-RGB-BLE"     # or use "addr" to connect directly to an address
  addr: null                       # e.g. "44:1D:64:F4:AC:D2" on Linux/Mac, GUID on Windows
  scan_timeout: 8.0                # seconds

capture:
  frequency_ms: 200
  output_root: "../captures"       # can also be in OneDrive; keeping it local is faster
  simulate_camera: false           # true = test mode (uses images from a folder)
  camera_type: "pylon"             # "opencv" for webcam or "pylon" for basler.
  camera_id: 0                     # webcam id (0 usually works)
  camera_serial: 23324651          # serial number for industrial cameras
  camera_ip: 192.168.1.165         # URL/IP for network cameras
  test_source_dir: "../image_to_be_used"   # used if simulate_camera=true

pose:
  enabled: true
  method: "cube"                   # "cube" | "custom"
  max_parallel_jobs: 3             # 3 is fine (CPU permitting)
  delete_frames_after_processing: false
  cube:
    dictionary: "4X4_50"
    marker_size_mm: 54.0      # marker side (only black portion)
    cube_size_mm: 60.0        # cube side
    pair_strategy: "max_angle"    # first or max_angle
    wand_offset_m: 0.17
    wand_directions:
      "0": "+X"
      "1": "+X"
      "2": "-X"
      "3": "+X"
      "4": "-Z"
  camera_calibration_npz: "../calib/calib_data.npz"  # must contain 'camera_matrix' and 'dist_coeffs'
  stream_file_settle_ms: 120  # time before start process image saved on disk

runtime:
  debug: false                      # extra debug behavior
  log_level: INFO                 # DEBUG, INFO, WARNING, ERROR
  log_to_file: false               # write global app.log in addition to console

plot:
  default_pose_json: "../captures/session_2025-09-30_15-42-09__2025-09-30_15-42-20_pose.json"
